spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

app:
  baseUrl: http://localhost:8080